# Generated by Django 3.0.5 on 2020-04-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000)),
                ('items_available', models.IntegerField(blank=True, null=True)),
                ('product_type', models.CharField(choices=[('bread', 'Bread'), ('cake', 'Cake'), ('drink', 'Drink')], default='bread', max_length=1000)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
